### ISSUE TITLE
Water shader it will work on HDRP?

### ISSUE THREAD

**Issue by GilbertoBitt** [Unity-Technologies/BoatAttack#109]
is no why? since is using shader graph and what I should do to make it work?

**Comment by pkpatel001** [comment]
The project is made using the URP pipeline which by default uses URP shaders so they are different from HDRP pipeline shaders, hence would not work.

**Comment by Verasl** [comment]
The waters rendering is closely tied to the universal rp and also uses custom shaders. There are no plans to convert it to HDRP at this point.

**Comment by FFHstudioHugo** [comment]
@GilbertoBitt If you want a comparable asset go buy Crest Ocean HDRP? valuable.
