### ISSUE TITLE
Env_Rocks and Sea materials are pink

### ISSUE THREAD

**Issue by sophiepeithos** [Unity-Technologies/BoatAttack#14]
However the shaders used by these two materials have no compile errors. I have LightWeight RP 4.1.0-preview installed locally.

**Comment by Verasl** [comment]
Does a reimport fix any issues? also which branch are you using?

**Comment by sophiepeithos** [comment]
I think may be I am switched to wrong branch

**Comment by ImanCol** [comment]
> Creo que puede ser que me cambien a rama equivocada

why delete my comment?

**Comment by ImanCol** [comment]
> I think may be I am switched to wrong branch

why delete my comment?
