### ISSUE TITLE
The project does not run in WebGl. 

### ISSUE THREAD

**Issue by ImanCol** [Unity-Technologies/BoatAttack#15]
After loading the Unity Banner the screen is completely blank.

Using the same version of Unity 2018.3.0b4

password: boat

https://www.newgrounds.com/projects/games/1268251/preview

**Comment by Verasl** [comment]
Would you be able to try again with LWRP version 4.6.0? WebGL should be working fine, if you fail to get a build running can you try disabling MSAA and/or Post-processing as either of these might be the culprit. 
Would love to hear what works for you.

**Comment by Verasl** [comment]
Loading the provided site works for me, it might be an issue with WebGL 1.0 as this project is not setup to work correctly and should be targeted to WebGL 2.0. Try using the latest Chrome or Firefox.

Closing as it does indeed does work.

**Comment by ImanCol** [comment]
WebGl 2.0 I do not find it in my latest version of Chrome. Also, other compilations of projects in Unity its work me in WebGL, only this one does not

**Comment by ImanCol** [comment]
![image](https://user-images.githubusercontent.com/26169049/52916479-f43ed400-32ad-11e9-9eb0-d619f6873c16.png)
