### ISSUE TITLE
Project looks Broken

### ISSUE THREAD

**Issue by deodatopr** [Unity-Technologies/BoatAttack#18]
Hello :) 

I did download the project in zip version and looks broken, because Im suing 2018.3.0b9 even 2019.1 and the scenes looks totally incomplete, even has tiffs images in where unity doesn't read thems.

am I doing something wrong?

Thanks,
Deo

**Comment by EnricoMonese** [comment]
Same, images and meshes are all unreadable

**Comment by Verasl** [comment]
Hey,

Yes all the meshes and images are stored in GitLFS and these unfortunately are not included in the zip that GitHub creates, you will have to clone down this project with a source control program such as Sourcetree or Fork.

I plan on uploading a few builds for different platforms but for now the best way to grab this is cloning it.

Cheers,
Andre
