### ISSUE TITLE
I saw the Unity scene Inverted in my HTC Vive Headset 

### ISSUE THREAD

**Issue by castana1962** [Unity-Technologies/BoatAttack#26]
Hi 
I am confusing myself because I am trying the SteamVR plugin 2.2.0 and Unity 2019.1 alpha version with this Lightweight Render Pipeline Boat Demo.
My problem is that that when I added the SteamVR Player or Camera Rig Prefab to it, I saw the Unity Scene Ok in the Editor Game tab but I saw this scene inverted in my HTC Vive Headset.
I did a new scene of this and added only the their Environment and the Steam VR plugin to it again and I have the same problem, to be honest I do not know what is the problem but I guess that the problem can be with Unity 2019 alpha version , for it, Could anybody advice me to fix it?
Thanks for your time

**Comment by huwb** [comment]
Interested in this - commenting here to get notifications about any status updates or timelines for fixes.

**Comment by castana1962** [comment]
Hi All
I did a Bug request in Unity . It is the Case 1141401.
If I have any answer, I will let know it here
Hope this helps !!!

**Comment by castana1962** [comment]
Hi All
This problem was fixed with 2019.1.0b10 version. I added the CameraRig prefab and I can the scene succesfully( Thanks to Bugs Unity people.....)
Now my problem is that I see frightful the Sea....(the SeaVerDisp prefab) and to be honest with you, I have no idea about how to fix it?
Could anybody help me to fix this problem?
Thanks
Alejandro
