### ISSUE TITLE
It's stuck when I open it

### ISSUE THREAD

**Issue by OtakuAndFitness** [Unity-Technologies/BoatAttack#27]
I download Packages/4.6.0 and use 2018.3.6f1 to open on MacOS 10.14.3, but it's stuck at this point
<img width="388" alt="2019-02-23 16 28 10" src="https://user-images.githubusercontent.com/9075980/53283945-3a050c00-3788-11e9-8b26-d8cde259b55e.png">

**Comment by OtakuAndFitness** [comment]
Finally I installed Unity2019.1.0b4 and downloaded Packages/5.3.0, then I successfully opened it. However, I encountered this problem and failed to run this game.
<img width="1095" alt="2019-02-27 11 13 01" src="https://user-images.githubusercontent.com/9075980/53463131-0a544d80-3a81-11e9-914d-6936acba5517.png">

**Comment by OtakuAndFitness** [comment]
Eventually I solved that, but there're still other errors.
<img width="1300" alt="2019-02-27 11 58 13" src="https://user-images.githubusercontent.com/9075980/53464974-2d81fb80-3a87-11e9-9d0c-95578a104f1e.png">

**Comment by Verasl** [comment]
The issue you saw in 19.1.0b4 is dues to version mismatch between LWRP(also this demo) and Unity, this would have caused compile and import issues that means even when fixed lead you to the errors in the third comment.

I'm working on an updated branch that will work with 19.1b6 and newer as this is the version of 19.1 where we will  no longer be changing API breaking changes won't be introduced going forwards to release.

**Comment by Verasl** [comment]
I have now updated and created a `release/2019.1` branch, this will work out of the box with current Unity 2019.1, please use this if you are still running into issues.

Cheers,
Andre
