### ISSUE TITLE
fails on 2019.1b4

### ISSUE THREAD

**Issue by joaquingrech** [Unity-Technologies/BoatAttack#28]
the prefabs lose links, the scripts go missing and when you manually fix it, it still won't run well. Also scripts have compile errors

**Comment by Verasl** [comment]
19.1 has gone under some heavy API changes in regards to SRP this has made this demo very finicky when it comes to which version of unity and which version of LWRP and also which version of this demo, luckily since 19.1b6 this should settle, I'm working on an updated branch with the latest LWRP package which will get this working again but with GDC and the release of 19.1 out of preview LWRP my time has disappeared.

I should have an updated branch in the next week or two.

**Comment by sergiosolorzano** [comment]
Hi any update on this please? It worked fine in 2018.3. Upgarding to 2019.1 can't compile. Below my packages and errors, guidance please, cheers!
![image](https://user-images.githubusercontent.com/24430655/57081739-41e3ae00-6ced-11e9-8c9e-07b5614d7a22.png)
![image](https://user-images.githubusercontent.com/24430655/57081770-5162f700-6ced-11e9-8b9b-7d1e50edda15.png)

**Comment by sergiosolorzano** [comment]
Hi @Verasl  has this project been abandoned?

**Comment by Verasl** [comment]
Hi @sergiosolorzano ! no it has not, have you tried to pull the latest `release/2019.1`? the branch should be working 100% with the released versions of 19.1 now(last tested on 19.1.0f2).

**Comment by sergiosolorzano** [comment]
Hi @Verasl , I tested by pulling the project as of today's version (12062019) in the saved 2019.1 version PC version and making no changes but it does not render correctly, here's what the island scene shows: https://drive.google.com/open?id=1VW1sl627E_lMH981EwElixJCzTftuuBO
I then switched platform to ios and it's the same. Looks like this water is leaking for me...

**Comment by danielcitron** [comment]
Hi @Verasl and @sergiosolorzano , I'm running into the same issue on 2019.1 (your screenshot looks identical to the rendering issues I'm having). Did you ever end up figuring out a solution?

**Comment by ChrisMa130** [comment]
I am having the same issues. Any news on the solutions now?

**Comment by ChrisMa130** [comment]
> Hi @Verasl and @sergiosolorzano , I'm running into the same issue on 2019.1 (your screenshot looks identical to the rendering issues I'm having). Did you ever end up figuring out a solution?

OK, I figured out the solution. Apparently you need to clone the project via Git for the meshes and textures to appear, instead of downloading the zip file and unzip it.

**Comment by Verasl** [comment]
Yes indeed, this project used GitLFS for all texture, meshes and other large files, you need to have GitLFS installed and then pull the project with git. I have just today added a download link for a 2019.3 version of the full project in the readme, so if you want to avoid getting it via git you can grab the zip from there.
