### ISSUE TITLE
Doesn't compile with Unity 2018.3.7f1

### ISSUE THREAD

**Issue by jBachalo** [Unity-Technologies/BoatAttack#33]
I get 561 compile errors when i try and open the project in Unity 2018.3.7f1
![Screen Shot 2019-03-13 at 12 05 42 PM](https://user-images.githubusercontent.com/247784/54306647-394de180-45a0-11e9-82d3-b212d1920286.png)

**Comment by Verasl** [comment]
LWRP 5.x.x is not supported in 18.3, and this project is no longer being maintained for 2018 releases f Unity due to LWRP not being maintained either. If you wish to use this project please update to 2019.1 at least and use the branch `release/2019.1`.

Cheers,
Andre
