### ISSUE TITLE
water problem on android

### ISSUE THREAD

**Issue by sophiepeithos** [Unity-Technologies/BoatAttack#35]
water has problem on android, seems parts of the water is missing.
running on samsung s9 plus, branch is release/2019.1
branch package/4.6.0 is the same
![Capture+_2019-03-21-16-57-10](https://user-images.githubusercontent.com/1758796/54741988-07b9c380-4bfb-11e9-8f35-bdf67210be01.png)

**Comment by ghost** [comment]
Did you solve this issue?

**Comment by aver1216** [comment]
Still exists. Some ideas how to fix?

**Comment by Verasl** [comment]
Closing this as it is related to https://github.com/Verasl/BoatAttack/issues/17
