### ISSUE TITLE
Water problem in HTC Vive VR Headset

### ISSUE THREAD

**Issue by castana1962** [Unity-Technologies/BoatAttack#36]
Hi All
I am trying this demo in HTC Vive VR Headset and I see very bad the Sea. The problem is with the  SeaVertDisp Game Object or rather with the Mesh Renderers on its children, for it, Does anybody how fix or modify it to avoid this annoying effect?
Thanks for your time
Best Regards
Alejandro

**Comment by Verasl** [comment]
Closing this issue as it's part of a larger issue of making sure the water works with VR, keeping this issue open for reference https://github.com/Verasl/BoatAttack/issues/37
