### ISSUE TITLE
repository over data quota

### ISSUE THREAD

**Issue by JoshSL** [Unity-Technologies/BoatAttack#41]
I am trying to clone the repo but I am getting this error.

batch response: This repository is over its data quota. Purchase more data packs                                                                         to restore access.

**Comment by JoshSL** [comment]
This error follows
error: failed to fetch some objects from 'https://github.com/Verasl/BoatAttack.g                                                                    it/info/lfs'

**Comment by Verasl** [comment]
Should be sorted now, thanks for the heads up
