### ISSUE TITLE
About the LFS files

### ISSUE THREAD

**Issue by cymhellfire** [Unity-Technologies/BoatAttack#45]
Hi, there.
First at all, I'd like to thank you for your awesome work to bring us a such project. But the LFS is an annoying issue happened every time I pull this repository from Github server. Log shows I got timeout and the pull process is shut down.
Would you consider to use another way to share the Mesh and Textures? It's really helpful for me to get the latest commit. Thank you very much.

**Comment by Verasl** [comment]
Hey @cymhellfire ,

This issue should be resolved, it was due to going over the traffic allowance on this end, let me know if you are still having issues. I plan to add zip files to the wiki so they can be downloaded without going via git if needed.

**Comment by cymhellfire** [comment]
Hi, @Verasl . 
Thank you for your effort on this problem. But unfortunately I still meet time out issue when pull the latest commit. Maybe it's also related to the network condition on my side.
It's much appreciated if you upload the zip files as an alternative way.
Thanks for your time, cheers.
