### ISSUE TITLE
Can you release android build for testing

### ISSUE THREAD

**Issue by Porush** [Unity-Technologies/BoatAttack#51]
Hi, I want to test the project on my android device, So if you release android build of the project it would be great.

Thanks

**Comment by zhuxianzhiniko** [comment]
> Hi, I want to test the project on my android device, So if you release android build of the project it would be great.
> 
> Thanks

I used version 2019.30a11 to release the app successfully. You can try it yourself.

**Comment by Porush** [comment]
Thanks, I will try it later. I just don't wanted to install GitLFS.
