### ISSUE TITLE
using HeightFog.hlsl on other project??

### ISSUE THREAD

**Issue by davoodkharmanzar** [Unity-Technologies/BoatAttack#52]
hello dear,
how can i using **HeightFog.hlsl** to other URP project?
is it possible?
thanks.

**Comment by Verasl** [comment]
Unfortunately not, this was made briefly to hack height fog into the Universal Render Pipeline, we have it on our road map to add better fog options to URP but for now this is just a floating un-usable file sorry.

**Comment by scriptsengineer** [comment]
What current state of the fog? Update?
