### ISSUE TITLE
Version mismatch for "Burst" in "Water" package dependencies

### ISSUE THREAD

**Issue by kimhutchison** [Unity-Technologies/BoatAttack#58]
**BoatAttack/Packages/com.verasl.water-system/package.json** as of https://github.com/Verasl/BoatAttack/commit/90a1395792a19cded7f3495acca405ed37f7ca6e

Reads:
`"com.unity.burst": "0.2.4-preview.30",`

But should read:
`"com.unity.burst": "1.1.2",`

**Comment by Verasl** [comment]
Same as the other issue you posted, they don't need to stay in sync, as long as references a minimum version it will work with. Latest commits have updated it to `1.0.0`
