### ISSUE TITLE
Version mismatch for "URP" in "Water" package dependencies

### ISSUE THREAD

**Issue by kimhutchison** [Unity-Technologies/BoatAttack#59]
**BoatAttack/Packages/com.verasl.water-system/package.json** as of https://github.com/Verasl/BoatAttack/commit/90a1395792a19cded7f3495acca405ed37f7ca6e

Reads:
`"com.unity.render-pipelines.universal": "7.0.0"`

But should read:
`"com.unity.render-pipelines.universal": "7.1.0"`

**Comment by Verasl** [comment]
Not necessarily, the water system just needs at least `7.0.0` and if pulled into a project alone without URP it will import `7.0.0`, but alas I have updated it to require `7.1.0` at minimum in the latest commits.
