### ISSUE TITLE
How to use this Project?

### ISSUE THREAD

**Issue by RenishParghi** [Unity-Technologies/BoatAttack#61]
I'm using Unity 2019.2.11f1 (64-bit) version and it keeps showing this mesh with pink color.

![Capture](https://user-images.githubusercontent.com/39672683/68525997-45d83480-02fd-11ea-9e7d-46d4f3fbe890.PNG)

I know I need to make assets for Universal render Pipeline but, it not showing any option to make these assets.
is there any problem??

**Comment by JFKS95** [comment]
I am using Unity 2019.3.0b10 and have this issue. Did you manage to rectify the problem?

**Comment by GetGitFiles** [comment]
Same.

**Comment by Siphonn** [comment]
Had the same issue while testing 2019.3.0b10 and the High Definition RP package 7.1.2.
Downgrading the HDRP package to 7.1.1 fixed the issue.

There could be a similar issue with URP package. Maybe try update the package version. 

![Untitled](https://user-images.githubusercontent.com/36541593/68780189-d0869f80-062d-11ea-9b12-24c1a685fcc7.png)

**Comment by Verasl** [comment]
> I know I need to make assets for Universal render Pipeline but, it not showing any option to make these assets.
> is there any problem??

By the looks of the error at the bottom you might be pulling down the wrong branch for 2019.2, make sure you are pulling `release/2019.2`, if you still have issues I'll have a look at that branch as I haven't updated it in a while and may need some work.

**Comment by Verasl** [comment]
I have updated the readme with more information and also a download link to a full version of the project for 19.3 if you choose not to pull the project with Git, if opening this in 19.3 is still giving you issues please open a new issue with some more information.
