### ISSUE TITLE
Everything is white, missing models, scripts, textures, etc.

### ISSUE THREAD

**Issue by Collcroc123** [Unity-Technologies/BoatAttack#63]
Using Unity 2019.3.0f3, everything appears like this. Some objects have no mesh, some have missing scripts, and all have no textures. How do I fix this?
![Unity_asdNJuB09S](https://user-images.githubusercontent.com/32398853/72745000-f10e3100-3b6b-11ea-9241-898e84faae63.png)

**Comment by Verasl** [comment]
You are missing all of the GitLFS content(meshes, textures, etc) if you want to pull from git you must install GitLFS, otherwise I have recently added a zip in the readme that is a complete version of the project for 19.3

**Comment by Collcroc123** [comment]
![image](https://user-images.githubusercontent.com/32398853/73039958-15d90180-3e15-11ea-8aa8-d4c59678b4e4.png)
I couldn't figure out GitLFS, so I downloaded that zip. it gives me this error every time I open the project. When I continue all of the assets are there, but then there's 5 errors that refuse to let me run scenes.
![image](https://user-images.githubusercontent.com/32398853/73040018-4e78db00-3e15-11ea-9fdb-3cdb3c721921.png)

**Comment by ImanCol** [comment]
> You are missing all of the GitLFS content(meshes, textures, etc) if you want to pull from git you must install GitLFS, otherwise I have recently added a zip in the readme that is a complete version of the project for 19.3

I downloaded the compressed version. I get the same error as the one above, by omitting and continuing on the console I get four or five errors. When I try to eliminate the commands that give errors in the script, the project does not work well.
