### ISSUE TITLE
Companion License Rolled to UT git

### ISSUE THREAD

**Issue by ghost** [Unity-Technologies/BoatAttack#66]
Old license is on Unity Technologies repo from 10 mo ago, looks like now it  is Unity Companion?
https://github.com/Unity-Technologies/BoatAttack/commit/a1cea4695d70b3940944e5659a0fc388742e1180#commitcomment-37037439

**Comment by Verasl** [comment]
Yes the Unity one is fallen behind, I'll need to reach out to who owns that, I will be looking at moving this repo over to the Unity GitHub soon. But yes the license is Unity Companion and this repo is the current official one.
