### ISSUE TITLE
"Race" button not working on Android

### ISSUE THREAD

**Issue by 4ian** [Unity-Technologies/BoatAttack#85]
I tried to build and run the latest `master` commit (9fc1b528231d53ae0b8d9b6a3f2e79f169f0769a) on Android.

When in the main menu I choose Race, then single player or spectator, then press the bottom right "Race" button, the game is not loading the level. Instead, I can see using adb logcat:

```
                  Unity  E  MissingMethodException: Default constructor not found for type UnityEngine.ResourceManagement.ResourceManager+CompletedOperation`1[[UnityEngine.GameObject, UnityEngine.CoreModule, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null]]
                         E    at System.RuntimeType.CreateInstanceMono (System.Boolean nonPublic) [0x00000] in <00000000000000000000000000000000>:0
                         E    at System.Activator.CreateInstance (System.Type type, System.Boolean nonPublic) [0x00000] in <00000000000000000000000000000000>:0
                         E    at UnityEngine.ResourceManagement.Util.LRUCacheAllocationStrategy.New (System.Type type, System.Int32 typeHash) [0x00000] in <00000000000000000000000000000000>:0
                         E    at UnityEngine.ResourceManagement.ResourceManager.CreateOperation[T] (System.Type actualType, System.Int32 typeHash, System.Int32 operationHash, System.Action`1[T] onDestroyAction) [0x00000] in <00000000000000000000000000000000>:0
                         E    at UnityEngine.ResourceManagement.ResourceManager.CreateCompletedOperation[TObject] (TObject result, System.String errorMsg) [0x0000
```

My setup is as follow:

* I've been using Unity 2019.3.0f3
* I've enabled ARM64 architecture
* The rest is what we get by default in the project:
  * Strip Engine Code is *not* activated.
  * Managed Stripping level is Low
  * I built the `main_menu` and `level_Island` scenes:
  ![image](https://user-images.githubusercontent.com/1280130/75896096-77d25100-5e2e-11ea-90dc-273d6efd9714.png)

The device is a Pixel 2 XL, which used to be able to run a previous version. It can also run the demo scene when I compile a game with this scene only. 

I've not yet tried the `release/2019.3` branch, I'll give it a try too when I can.

**Comment by AlexChesser** [comment]
I actually came here to report the exact same issue on the exact same phone.

```
MissingMethodException: Default constructor not found for type UnityEngine.ResourceManagement.ResourceManager+CompletedOperation`1[[UnityEngine.GameObject, UnityEngine.CoreModule, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null]]
03-05 15:54:36.005 20391 20413 E Unity   :   at System.RuntimeType.CreateInstanceMono (System.Boolean nonPublic) [0x00000] in <00000000000000000000000000000000>:0
03-05 15:54:36.005 20391 20413 E Unity   :   at System.Activator.CreateInstance (System.Type type, System.Boolean nonPublic) [0x00000] in <00000000000000000000000000000000>:0
03-05 15:54:36.005 20391 20413 E Unity   :   at UnityEngine.ResourceManagement.Util.LRUCacheAllocationStrategy.New (System.Type type, System.Int32 typeHash) [0x00000] in <00000000000000000000000000000000>:0
03-05 15:54:36.005 20391 20413 E Unity   :   at UnityEngine.ResourceManagement.ResourceManager.CreateOperation[T] (System.Type actualType, System.Int32 typeHash, System.Int32 operationHash, System.Action`1[T] onDestroyAction) [0x00000] in <00000000000000000000000000000000>:0
03-05 15:54:36.005 20391 20413 E Unity   :   at UnityEngine.ResourceManagement.ResourceManager.CreateCompletedOperation[TObject] (TObject result, System.String errorMsg) [0x0000
```

I'll try that 2019.3 branch.  (edit: confirmed as broken)
Unity version `2019.3.3f1` 


edit2:  @4ian did you run the `build addressables` step?  It is listed in the readme and I missed it.  And trying now to see if that fixes it.

edit3:   can now confirm that (for me) build for android does work if you build adressables first.

step one
![image](https://user-images.githubusercontent.com/355561/76027911-791f7e80-5eff-11ea-9272-ea1a083c756d.png)

step two
![image](https://user-images.githubusercontent.com/355561/76027960-8f2d3f00-5eff-11ea-8071-25b5f3221a77.png)

then build and run as normal

**Comment by 4ian** [comment]
Can confirm this works! I totally missed the instruction about rebuilding adressables.
Thanks @AlexChesser! Marking this as closed - though maybe this should be highlighted in the README or even warned when building on Unity side?
